name: ROS workspace CI

on: [push, pull_request]

jobs:
  build:
    # test multiple Ubuntu and ROS distributions
    # https://github.com/ros-tooling/setup-ros#iterating-on-all-ros-distributions-for-all-platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution: [noetic, humble]
        include:
          - docker_image: ubuntu:20.04
            cuda_distribution: ubuntu2004
            ros_distribution: noetic
            ros_version: 1

          - docker_image: ubuntu:22.04
            cuda_distribution: ubuntu2204
            ros_distribution: humble
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: install core dependencies
        run: |
          apt update
          apt install --no-install-recommends -y ca-certificates gnupg wget software-properties-common

      - name: setup CUDA repository
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.cuda_distribution }}/x86_64/cuda-${{ matrix.cuda_distribution }}.pin
          mv cuda-${{ matrix.cuda_distribution }}.pin /etc/apt/preferences.d/cuda-repository-pin-600
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.cuda_distribution }}/x86_64/3bf863cc.pub
          add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.cuda_distribution }}/x86_64/ /"

      - name: install CUDA (Ubuntu 20.04)
        if: ${{ matrix.docker_image == 'ubuntu:20.04' }}
        run: |
          apt install --no-install-recommends -y libcurand-dev-11-3 libcufft-dev-11-3 libcublas-dev-11-3 cuda-nvcc-11-3 cuda-nvtx-11-3 libcudnn8-dev

      - name: install CUDA (Ubuntu 22.04)
        if: ${{ matrix.docker_image == 'ubuntu:22.04' }}
        run: |
          apt install --no-install-recommends -y libcurand-dev-11-7 libcufft-dev-11-7 libcublas-dev-11-7 cuda-nvcc-11-7 cuda-nvtx-11-7
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcudnn8_8.4.0.27-1+cuda11.6_amd64.deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcudnn8-dev_8.4.0.27-1+cuda11.6_amd64.deb
          dpkg -i libcudnn8_8.4.0.27-1+cuda11.6_amd64.deb libcudnn8-dev_8.4.0.27-1+cuda11.6_amd64.deb

      - uses: actions/checkout@v3

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.3

      - name: ROS 1 CI Action
        if: ${{ matrix.ros_version == 1 }}
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: super_point_inference
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: .github/dependencies.yaml

      - name: ROS 2 CI Action
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: super_point_inference
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: .github/dependencies.yaml
