name: ROS workspace CI

on: [push, pull_request]

jobs:
  build:
    # test multiple Ubuntu and ROS distributions
    # https://github.com/ros-tooling/setup-ros#iterating-on-all-ros-distributions-for-all-platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution: [noetic, humble]
        include:
          - docker_image: ubuntu:20.04
            ros_distribution: noetic
            ros_version: 1

          - docker_image: ubuntu:22.04
            ros_distribution: humble
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: install core dependencies
        run: |
          apt update
          apt install --no-install-recommends -y ca-certificates gnupg wget software-properties-common

      - name: install CUDA (Ubuntu 20.04)
        if: ${{ matrix.docker_image == 'ubuntu:20.04' }}
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
          add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
          apt install --no-install-recommends -y libcurand-dev-11-3 libcufft-dev-11-3 libcublas-dev-11-3 cuda-nvcc-11-3 cuda-nvtx-11-3 cuda-nvrtc-dev-11-3 libcudnn8-dev

      - name: install CUDA (Ubuntu 22.04)
        if: ${{ matrix.docker_image == 'ubuntu:22.04' }}
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          dpkg -i cuda-keyring_1.1-1_all.deb
          rm cuda-keyring_1.1-1_all.deb
          apt update
          apt install --no-install-recommends -y libcurand-dev-11-8 libcufft-dev-11-8 libcublas-dev-11-8 cuda-nvcc-11-8 cuda-nvtx-11-8 cuda-nvrtc-dev-11-8 libcudnn8-dev

      - uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7

      - name: ROS 1 CI Action
        if: ${{ matrix.ros_version == 1 }}
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: super_point_inference
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: .github/dependencies.yaml

      - name: ROS 2 CI Action
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: super_point_inference
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: .github/dependencies.yaml
